--Version for double suction cup--================START of AutoMove()================
local Default_Option={CP=1, SpeedJ=50, AccJ=20, SpeedL=50, AccL=20}
--[[Program generated by RoboDK v5.6.7 for Dobot MG400 on 31/01/2024 16:42:52--]]
--[[Using nominal kinematics.--]]
MovJ({armOrientation="right", coordinate={250.004,135.000,-166.000,180.000}, joint={28.368600,60.886400,82.865300,28.358600}, tool=0, user=0 }, Default_Option)
MovL({armOrientation="right", coordinate={250.004,135.000,-186.000,180.000}, tool=0, user=0 }, Default_Option)
--[[Attach to Suction Cup--]]
DO(1,ON)
Wait(1000)
MovL({armOrientation="right", coordinate={250.004,135.000,-166.000,180.000}, tool=0, user=0 }, Default_Option)
MovJ({armOrientation="right", coordinate={300.004,-125.000,-166.000,180.000}, joint={-22.619600,64.056400,70.596100,-22.629600}, tool=0, user=0 }, Default_Option)
MovL({armOrientation="right", coordinate={300.004,-125.000,-186.000,180.000}, tool=0, user=0 }, Default_Option)
--[[Detach from Suction Cup--]]
DO(1,OFF)
Wait(1000)
MovL({armOrientation="right", coordinate={300.004,-125.000,-166.000,180.000}, tool=0, user=0 }, Default_Option)
MovJ({armOrientation="right", coordinate={250.009,110.000,-166.000,180.000}, joint={23.748800,60.514900,86.296600,23.738800}, tool=0, user=0 }, Default_Option)
MovL({armOrientation="right", coordinate={250.009,110.000,-186.000,180.000}, tool=0, user=0 }, Default_Option)
--[[Attach to Suction Cup--]]
DO(1,ON)
Wait(1000)
MovL({armOrientation="right", coordinate={250.009,110.000,-166.000,180.000}, tool=0, user=0 }, Default_Option)
MovJ({armOrientation="right", coordinate={300.009,-150.000,-166.000,180.000}, joint={-26.564400,65.279100,67.504900,-26.574400}, tool=0, user=0 }, Default_Option)
MovL({armOrientation="right", coordinate={300.009,-150.000,-186.000,180.000}, tool=0, user=0 }, Default_Option)
--[[Detach from Suction Cup--]]
DO(1,OFF)
Wait(1000)
MovL({armOrientation="right", coordinate={300.009,-150.000,-166.000,180.000}, tool=0, user=0 }, Default_Option)

--================END of AutoMove()================
